INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');



INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER )
VALUES ('Λασιθίου', 'Άγιος Νικόλαος',35.19 , 105, 13, 18.02, 0.928, 0.95,0.9, 0.99, 0.98, 0.98, 0.754399578, 0.85,3.483870968);


INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Αθηνών','Αθήνα',37.9838,108,12,16.88,0.932,0.95,0.9,0.99,0.98,0.98,0.757651301,0.85,3.483870968);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Έβρου','Αλεξανδρούπολη',40.8457,79,7,16.13,0.952,0.95,0.9,0.99,0.98,0.98,0.773909912,0.85,2.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Φωκίδας','Άμφισσα',38.5267,79,7.7,13.56,0.9492,0.95,0.9,0.99,0.98,0.98,0.771633707,0.85,2.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κεφαλληνίας','Αργοστόλι',38.1732,86,12.8,18.33,0.9288,0.95,0.9,0.99,0.98,0.98,0.755049923,0.85,2.774193548);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Άρτας','Άρτα',39.1582,88,10.7,16.77,0.9372,0.95,0.9,0.99,0.98,0.98,0.76187854,0.85,2.838709677);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ημαθίας','Βέροια',40.5194,77,6.6,13.81,0.9536,0.95,0.9,0.99,0.98,0.98,0.775210601,0.85,2.483870968);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Μαγνησίας','Βόλος',39.3666,78,9,16.93,0.944,0.95,0.9,0.99,0.98,0.98,0.767406468,0.85,2.516129032);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Γρεβενών','Γρεβενά',40.0838,59,6,12.83,0.956,0.95,0.9,0.99,0.98,0.98,0.777161634,0.85,1.903225806);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Δράμας','Δράμα',41.1502,73,8.6,16.07,0.9456,0.95,0.9,0.99,0.98,0.98,0.768707156,0.85,2.35483871);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Πέλλας','Έδεσσα',40.8017,79,6.6,14.13,0.9536,0.95,0.9,0.99,0.98,0.98,0.775210601,0.85,2.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κυκλάδων','Ερμούπολη',37.45,110,15,18.55,0.92,0.95,0.9,0.99,0.98,0.98,0.747896134,0.85,3.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ζακύνθου','Ζάκυνθος',37.7882,92,14.7,18.51,0.9212,0.95,0.9,0.99,0.98,0.98,0.74887165,0.85,2.967741935);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Θεσπρωτίας','Ηγουμενίτσα',39.5061,79,9,16.48,0.944,0.95,0.9,0.99,0.98,0.98,0.767406468,0.85,2.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ηρακλείου','Ηράκλειο',35.3387,103,12.5,18.66,0.93,0.95,0.9,0.99,0.98,0.98,0.756025439,0.85,3.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Θεσσαλονίκης','Θεσσαλονίκη',40.6401,72,9.4,15.38,0.9424,0.95,0.9,0.99,0.98,0.98,0.766105779,0.85,2.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ιωαννίνων','Ιωάννινα',39.665,72,6.9,13.28,0.9524,0.95,0.9,0.99,0.98,0.98,0.774235084,0.85,2.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Καβάλας','Καβάλα',40.9376,66,7,15.98,0.952,0.95,0.9,0.99,0.98,0.98,0.773909912,0.85,2.129032258);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Μεσσηνίας','Καλαμάτα',37.0366,97,13.7,18.88,0.9252,0.95,0.9,0.99,0.98,0.98,0.752123373,0.85,3.129032258);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Καρδίτσας','Καρδίτσα',39.364,72,8.6,15.31,0.9456,0.95,0.9,0.99,0.98,0.98,0.768707156,0.85,2.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ευρυτανίας','Καρπενήσι',38.9121,76,6.4,12.57,0.9544,0.95,0.9,0.99,0.98,0.98,0.775860946,0.85,2.451612903);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Άγιο Όρος','Καρυές',37.291,47,5,15.69,0.96,0.95,0.9,0.99,0.98,0.98,0.780413357,0.85,1.516129032);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Καστοριάς','Καστοριά',40.5193,62,5.2,12.59,0.9592,0.95,0.9,0.99,0.98,0.98,0.779763012,0.85,2);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Πιερίας','Κατερίνη',40.2702,78,10.2,16.12,0.9392,0.95,0.9,0.99,0.98,0.98,0.763504401,0.85,2.516129032);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κέρκυρας','Κέρκυρα',39.6243,79,12.6,17.18,0.9296,0.95,0.9,0.99,0.98,0.98,0.755700267,0.85,2.548387097);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κιλκίς','Κιλκίς',40.9937,71,7.8,15.47,0.9488,0.95,0.9,0.99,0.98,0.98,0.771308534,0.85,2.290322581);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κοζάνης','Κοζάνη',40.3006,74,5.2,12.38,0.9592,0.95,0.9,0.99,0.98,0.98,0.779763012,0.85,2.387096774);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ροδόπης','Κομοτηνή',41.1224,92,8.3,14.83,0.9468,0.95,0.9,0.99,0.98,0.98,0.769682673,0.85,2.967741935);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Κορινθίας','Κόρινθος',37.9386,95,10.8,16.73,0.9368,0.95,0.9,0.99,0.98,0.98,0.761553367,0.85,3.064516129);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Φθιώτιδας','Λαμία',38.8997,81,8.8,14.68,0.9448,0.95,0.9,0.99,0.98,0.98,0.768056812,0.85,2.612903226);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Λάρισας','Λάρισα',39.639,85,9.5,16.51,0.942,0.95,0.9,0.99,0.98,0.98,0.765780606,0.85,2.741935484);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Λευκάδας','Λευκάδα',38.8334,86,11.5,17.52,0.934,0.95,0.9,0.99,0.98,0.98,0.759277162,0.85,2.774193548);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Βοιωτίας','Λιβαδειά',38.4387,73,7,15.15,0.952,0.95,0.9,0.99,0.98,0.98,0.773909912,0.85,2.35483871);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Αιτωλοακαρνανίας','Μεσολόγγι',38.3687,98,9.6,17.63,0.9416,0.95,0.9,0.99,0.98,0.98,0.765455434,0.85,3.161290323);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Λέσβου','Μυτιλήνη',39.1067,90,12.2,17.35,0.9312,0.95,0.9,0.99,0.98,0.98,0.757000956,0.85,2.903225806);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Αργολίδας','Ναύπλιο',37.5673,93,9.5,17.34,0.942,0.95,0.9,0.99,0.98,0.98,0.765780606,0.85,3);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ξάνθης','Ξάνθη',41.1363,81,8.4,14.67,0.9464,0.95,0.9,0.99,0.98,0.98,0.769357501,0.85,2.612903226);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Αχαΐας','Πάτρα',38.2466,107,10,15.54,0.94,0.95,0.9,0.99,0.98,0.98,0.764154745,0.85,3.451612903);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Πειραιώς','Πειραιάς',37.943,98,12,16.88,0.932,0.95,0.9,0.99,0.98,0.98,0.757651301,0.85,3.161290323);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Χαλκιδικής','Πολύγυρος',40.3816,60,10.5,16.35,0.938,0.95,0.9,0.99,0.98,0.98,0.762528884,0.85,1.935483871);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Πρέβεζας','Πρέβεζα',39.2023,92,9,17.67,0.944,0.95,0.9,0.99,0.98,0.98,0.767406468,0.85,2.967741935);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ηλείας','Πύργος',37.67,102,11,17.4,0.936,0.95,0.9,0.99,0.98,0.98,0.760903023,0.85,3.290322581);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ρεθύμνης','Ρέθυμνο',35.3656,84,12,17.4,0.932,0.95,0.9,0.99,0.98,0.98,0.757651301,0.85,2.709677419);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Δωδεκανήσου','Ρόδος',36.435,103,16,19.91,0.916,0.95,0.9,0.99,0.98,0.98,0.744644411,0.85,3.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Σάμου','Σάμος',37.7548,107,14,18.04,0.924,0.95,0.9,0.99,0.98,0.98,0.751147856,0.85,3.451612903);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Σερρών','Σέρρες',41.0864,72,8.9,16.77,0.9444,0.95,0.9,0.99,0.98,0.98,0.76773164,0.85,2.322580645);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Λακωνίας','Σπάρτη',37.0745,93,9.2,15.04,0.9432,0.95,0.9,0.99,0.98,0.98,0.766756123,0.85,3);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Τρικάλων','Τρίκαλα',39.5557,73,8.8,15.89,0.9448,0.95,0.9,0.99,0.98,0.98,0.768056812,0.85,2.35483871);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Αρκαδίας','Τρίπολη',37.5101,87,7.5,13.75,0.95,0.95,0.9,0.99,0.98,0.98,0.772284051,0.85,2.806451613);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Φλώρινας','Φλώρινα',40.7845,62,3.5,10.23,0.966,0.95,0.9,0.99,0.98,0.98,0.78529094,0.85,2);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Ευβοίας','Χαλκίδα',38.4687,84,10.7,17.64,0.9372,0.95,0.9,0.99,0.98,0.98,0.76187854,0.85,2.709677419);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Χανίων','Χανιά',35.5138,98,10.3,15.33,0.9388,0.95,0.9,0.99,0.98,0.98,0.763179229,0.85,3.161290323);
INSERT INTO DISTRICT (DISTRICT_NAME, CAPITAL, LATITUDE, SOLAR_RADIATION_ON_DECEMBER, MEDIAN_TEMPERATURE_ON_DECEMBER,
	MEDIAN_TEMPERATURE_YEARLY, COEFFICIENT_OF_TEMPERATURE_CORRECTION, COEFFICIENT_OF_POLLUTION, COEFFICIENT_OF_AGEING,
	COEFFICIENT_OF_INPUT_LOSSES, COEFFICEINT_OF_HETEROGENEITY, COEFFICIENT_OF_CABLING, COEFFICIENT_OF_SOLAR_PANEL_LOSSES,
	COEFFICIENT_OF_ENERGY_TRANSFER_LOSSES,SOLAR_DENSITY_ON_DECEMBER ) VALUES('Χίου','Χίος',38.371,101,11.1,15.5,0.9356,0.95,0.9,0.99,0.98,0.98,0.760577851,0.85,3.258064516);




insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.8,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.8,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',27,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.2,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.7,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.9,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.8,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.8,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.4,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.7,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',24.6,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.4,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.9,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.4,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.6,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.9,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',27.7,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.8,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',22.8,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.3,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.9,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.1,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.4,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.1,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',22.9,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.9,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.6,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',24.5,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.6,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.8,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',24.8,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.3,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.2,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',28.1,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.1,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.1,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.8,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.9,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.3,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.9,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.6,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.9,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.4,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',27.9,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',24.7,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',26.8,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',24.4,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',20.4,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',27,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',23.2,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Αύγουστος',25.1,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.2,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.4,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.1,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',22.9,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.3,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.4,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.1,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',23.9,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.1,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.7,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.7,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.1,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.1,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.9,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.9,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.6,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.4,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',22.5,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.2,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',23.9,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.4,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.7,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',23,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.9,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.3,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.7,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.2,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.9,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.7,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.8,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.1,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.6,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.9,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.4,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.8,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.8,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.6,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.1,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.5,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',28.1,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',24.4,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',27.3,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',23.8,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',20.3,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',26.7,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',22.8,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούλιος',25.1,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.2,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.6,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',19.6,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.5,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21.2,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.4,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',19.7,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.2,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.2,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.3,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.7,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.1,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',20,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.6,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',27.7,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21.9,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',18,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.4,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',20.1,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.1,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.3,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.6,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',19.3,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.47,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.5,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.8,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21.3,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.1,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.5,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.4,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.4,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.6,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.3,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',26.4,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',24.1,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',25.3,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',22.5,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',20,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',17.3,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.9,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',21.4,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Σεπτέμβριος',23.4,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.4,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.1,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.3,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.8,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.5,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.8,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.9,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.9,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.4,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23.5,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.2,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',18.8,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.8,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.3,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',18.4,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.7,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.1,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.2,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',20.9,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23.3,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.1,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.3,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.7,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.4,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24.3,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.1,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.4,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.6,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',20.6,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.2,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.7,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',21.8,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.1,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.5,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22.5,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',22,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23.9,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',20.8,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',23.1,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.8,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',16.4,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',24.4,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',19.7,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιούνιος',2.1,53);


insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.9,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.7,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.6,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',15,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.5,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17.6,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',15.4,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.4,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',13.8,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17.8,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',15.7,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',21.6,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.8,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17.7,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',21.3,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17.6,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',13.9,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.1,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.5,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',13.8,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.8,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',13.6,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.3,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.8,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',13.7,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.8,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.6,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.4,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.2,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.2,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.9,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.3,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.9,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.3,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.5,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17.1,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.7,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.8,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.1,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.8,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.6,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',22.9,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.8,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.7,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',16.5,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',17,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',14.9,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',11.5,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',20.5,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',18.1,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Οκτώβριος',19.6,53);


insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.9,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.6,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.3,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.9,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.8,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.2,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',17.3,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.5,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.2,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',17.8,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.3,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.1,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.4,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',21.2,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.1,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.5,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',17.6,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.6,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.4,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.2,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.3,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.5,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.3,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.8,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.2,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.9,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.6,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.6,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.1,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.1,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.2,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.3,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.8,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.8,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',16.7,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.9,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.6,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.2,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.6,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.8,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.6,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.3,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.9,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19.6,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.2,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',19,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',17.6,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',13.7,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',20.7,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',17.8,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάιος',18.6,53);


insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',15.13,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.5,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11.1,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9.3,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',16.9,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.6,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',8.3,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.8,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',7.5,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',10,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',8.1,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',16.4,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',16.9,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',13.2,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14.7,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',10.4,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',8.2,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11.4,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',15.5,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9.8,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',7.7,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',13.9,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',6.9,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11.7,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14.9,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9.3,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',6.9,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.5,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9.5,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11.1,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',15.1,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',10.9,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',15,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',13.9,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.5,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9.3,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11.8,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12.5,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14.8,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14.1,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',18.8,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',15.6,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',10.5,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',11,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',10.4,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',9,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',5.4,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',13.4,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',12,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Νοέμβριος',14.2,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.7,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.9,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12.4,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',10.3,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.7,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.7,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.3,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.7,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',9.7,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.5,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.9,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',15.3,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.9,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.4,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.8,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12.7,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',10.6,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12.6,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',15.6,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',9.5,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.2,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',9.6,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.3,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.9,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',9.4,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.6,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.1,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.5,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.4,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.9,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.6,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.6,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13.7,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.6,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12.4,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.9,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',13,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.2,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.1,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',16.6,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',15,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.4,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',12.6,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',10.7,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',7.3,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.4,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',11.9,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Απρίλιος',14.1,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',13.1,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.5,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.1,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',7.7,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',14.6,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.7,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',6.6,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.7,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',5.9,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.6,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',6.6,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',14.9,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',14.7,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',11.6,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.5,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',6.9,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.9,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',13.7,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.6,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',6.4,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.4,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',5.2,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.2,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.6,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',7.8,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',5.2,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.3,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.8,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.5,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',13.1,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.2,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.8,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.2,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.8,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.4,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.5,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.5,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.7,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.1,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',16.1,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',13.9,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.9,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',9.2,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',8.8,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',7.5,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',3.5,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',11.5,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',10.3,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Δεκέμβριος',12.5,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.8,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.4,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.8,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',8.2,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',13.5,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.6,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',8.4,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.5,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',7.2,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.6,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',8.4,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',14.1,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',13.7,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.3,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.7,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.9,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',8,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.3,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',13.3,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',7.4,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.7,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',6.9,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.7,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.1,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.7,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',6.7,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.1,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.4,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.5,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.6,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.5,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.6,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.1,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.5,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.4,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.5,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.6,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.1,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',14.8,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',13.2,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.1,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',9.5,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.4,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',8.2,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',4.5,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',11.8,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',10.1,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Μάρτιος',12.1,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.3,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.4,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.3,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',6.2,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',13,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9.4,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',5.5,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',4.8,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.6,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',4.9,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',12.7,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',13.1,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9.7,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10.9,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.4,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',5.5,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.3,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.4,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.36,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',5.2,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10.6,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',3.9,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.8,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.1,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',6.9,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',4.2,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',6.6,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9.1,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',6.8,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.4,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.7,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.1,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9.3,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',6.7,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.4,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.4,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.6,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.2,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10.4,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',13.7,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',11.5,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.6,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',7.9,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',5.9,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',2.1,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',9.3,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',8.8,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Φεβρουάριος',10.1,53);

insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.8,1);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.7,2);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6,3);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.3,4);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',12.7,5);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',7.2,6);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',2.5,7);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',7.3,8);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',2.4,9);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',5,10);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',2.3,11);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',12.3,12);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',12.6,13);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.2,14);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.1,15);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.3,16);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',3.4,17);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6.5,18);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.3,19);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.6,20);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',2.9,21);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',9.1,22);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',1.7,23);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6.5,24);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.4,25);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',3.4,26);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',2,27);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.1,28);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',7.4,29);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.3,30);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',5.2,31);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.3,32);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',5.9,33);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.1,34);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.8,35);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6.9,36);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.7,37);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6.5,38);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.7,39);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',6.3,40);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',9.9,41);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.5,42);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',9.7,43);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',13.9,44);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',10.6,45);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.8,46);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',5.6,47);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',4.9,48);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',3.2,49);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',0.4,50);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',8.1,51);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',7.8,52);
insert into monthly_temperature(MONTH_NAME, TEMPERATURE, DISTRICT_ID) values('Ιανουάριος',9.1,53);