version: '3'
services:
  orion:
    restart: always
    container_name: orion
    image: orion:v1
    build: ./thesis/
    volumes:
      - ~/docker/orion:/orion/logs
    ports:
      - "8082:8080"

  orionui:
    restart: always
    container_name: orionui
    image: orionui:v1
    build: ./orion-ngx/
    depends_on:
      - orion
    volumes:
      - ~/docker/orion:/orion/logs
    ports:
      - "8083:80"